apiVersion: 1
datasources:

- name: tempo
  uid: tempo
  type: tempo
  access: proxy
  url: http://tempo:3200
  basicAuth: false
  apiVersion: 1
  jsonData:
    httpMethod: GET
    serviceMap:
      datasourceUid: prometheus
    nodeGraph:
      enabled: true
    tracesToLogsV2:
      customQuery: true
      query: '{appname="grafana"} |~ "\\\\\"traceID\\\\\":\\\\\"$${__trace.traceId}\\\\"'
      spanEndTimeShift: 1m
      spanStartTimeShift: -1m
      datasourceUid: loki
      filterByTraceID: false
    lokiSearch:
      datasourceUid: loki
   
- name: prometheus
  uid: prometheus
  type: prometheus
  access: proxy
  url: http://prometheus:9090
  jsonData:
    timeInterval: 60s
    httpMethod: POST

- name: loki
  uid: loki
  type: loki
  access: proxy 
  url: http://loki:3100
  basicAuth: false
  jsonData:
    derivedFields:
      - datasourceUid: tempo
        matcherRegex: 'traceID\\":\\"([a-z0-9]+)\\"'
        name: TraceID
        url: $${__value.raw}
        urlDisplayLabel: Find this trace in Tempo

- name: pyroscope
  uid: phlare
  type: phlare
  access: proxy
  url: http://pyroscope:4040
  version: 1
  jsonData:
    minStep: 15s
    backendType: pyroscope

